import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const BACKUP_EMAIL = "digiwebdex@gmail.com";

const TABLES = [
  "profiles",
  "bookings",
  "booking_members",
  "booking_documents",
  "payments",
  "packages",
  "installment_plans",
  "hotels",
  "hotel_rooms",
  "hotel_bookings",
  "moallems",
  "moallem_payments",
  "moallem_commission_payments",
  "supplier_agents",
  "supplier_agent_payments",
  "expenses",
  "transactions",
  "accounts",
  "financial_summary",
  "notification_logs",
  "notification_settings",
  "user_roles",
  "site_content",
  "company_settings",
  "blog_posts",
  "cms_versions",
];

function toCsv(rows: Record<string, unknown>[]): string {
  if (!rows || rows.length === 0) return "";
  const headers = Object.keys(rows[0]);
  const lines = [headers.join(",")];
  for (const row of rows) {
    const values = headers.map((h) => {
      const val = row[h];
      if (val === null || val === undefined) return "";
      const str = typeof val === "object" ? JSON.stringify(val) : String(val);
      // Escape CSV: wrap in quotes if contains comma, quote, or newline
      if (str.includes(",") || str.includes('"') || str.includes("\n")) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    });
    lines.push(values.join(","));
  }
  return lines.join("\n");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const resendApiKey = Deno.env.get("RESEND_API_KEY");

    if (!resendApiKey) {
      throw new Error("RESEND_API_KEY not configured");
    }

    const supabase = createClient(supabaseUrl, serviceRoleKey);

    const today = new Date().toISOString().split("T")[0];
    const attachments: { filename: string; content: string }[] = [];
    const tableStats: { name: string; rows: number }[] = [];

    // Fetch all tables
    for (const table of TABLES) {
      try {
        const { data, error } = await supabase.from(table).select("*");
        if (error) {
          console.warn(`Failed to fetch ${table}: ${error.message}`);
          tableStats.push({ name: table, rows: -1 });
          continue;
        }
        const rows = data || [];
        tableStats.push({ name: table, rows: rows.length });
        if (rows.length > 0) {
          const csv = toCsv(rows);
          // Base64 encode for email attachment
          const encoded = btoa(
            new TextEncoder()
              .encode(csv)
              .reduce((s, b) => s + String.fromCharCode(b), "")
          );
          attachments.push({
            filename: `${table}_${today}.csv`,
            content: encoded,
          });
        }
      } catch (e) {
        console.warn(`Error processing ${table}:`, e);
        tableStats.push({ name: table, rows: -1 });
      }
    }

    // Build summary HTML
    const summaryHtml = `
      <h2>📦 Daily Database Backup — ${today}</h2>
      <p>TRIP TASTIC — সকল টেবিলের CSV ব্যাকআপ</p>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse; font-family:monospace; font-size:13px;">
        <tr style="background:#1a1a2e; color:#fff;"><th>Table</th><th>Rows</th></tr>
        ${tableStats
          .map(
            (t) =>
              `<tr><td>${t.name}</td><td style="text-align:right">${t.rows === -1 ? "⚠️ Error" : t.rows}</td></tr>`
          )
          .join("")}
      </table>
      <p style="margin-top:16px; color:#666; font-size:12px;">Auto-generated by TRIP TASTIC backup system</p>
    `;

    // Send email via Resend
    const emailPayload: Record<string, unknown> = {
      from: Deno.env.get("NOTIFICATION_FROM_EMAIL") || "backup@resend.dev",
      to: [BACKUP_EMAIL],
      subject: `📦 TRIP TASTIC Daily Backup — ${today}`,
      html: summaryHtml,
      attachments: attachments.map((a) => ({
        filename: a.filename,
        content: a.content,
      })),
    };

    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(emailPayload),
    });

    const emailResult = await emailRes.json();

    if (!emailRes.ok) {
      console.error("Resend error:", emailResult);
      throw new Error(`Email send failed: ${JSON.stringify(emailResult)}`);
    }

    console.log(`Backup sent to ${BACKUP_EMAIL}:`, emailResult);

    return new Response(
      JSON.stringify({
        success: true,
        tables: tableStats.length,
        attachments: attachments.length,
        email: emailResult,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Backup error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
