import { useEffect, useState } from "react";
import { apiClient } from "@/lib/apiClient";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

const DEFAULT_LABELS = {
  statement_title: "Statement Report",
  statement_subtitle: "Customer statement with BDT/SAR and running balance.",
  invoice_footer_note: "Bookings are subject to company terms and applicable service rules.",
  voucher_footer_note: "This voucher is generated by Tuba Al Hijaz operations system.",
};

export default function AdminContentLabelsManager() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [labels, setLabels] = useState(DEFAULT_LABELS);

  useEffect(() => {
    (async () => {
      const { data } = await apiClient
        .from("company_settings")
        .select("setting_value")
        .eq("setting_key", "content_labels")
        .maybeSingle();

      const cfg = (data as any)?.setting_value;
      if (cfg && typeof cfg === "object") {
        setLabels({ ...DEFAULT_LABELS, ...cfg });
      }

      setLoading(false);
    })();
  }, []);

  const save = async () => {
    setSaving(true);

    const existing = await apiClient
      .from("company_settings")
      .select("id")
      .eq("setting_key", "content_labels")
      .maybeSingle();

    let result;
    if ((existing.data as any)?.id) {
      result = await apiClient
        .from("company_settings")
        .update({ setting_value: labels })
        .eq("id", (existing.data as any).id);
    } else {
      result = await apiClient
        .from("company_settings")
        .insert({ setting_key: "content_labels", setting_value: labels });
    }

    setSaving(false);
    if (result.error) {
      toast.error(result.error.message);
      return;
    }
    toast.success("Content labels saved");
  };

  if (loading) return <p className="text-sm text-muted-foreground">Loading content labels...</p>;

  return (
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground">
        Update key titles and footer text blocks used in reports and printable documents.
      </p>

      <div className="grid gap-3">
        <label className="space-y-1">
          <span className="text-sm font-medium">Statement Title</span>
          <input
            className="w-full bg-secondary border border-border rounded-md px-3 py-2 text-sm"
            value={labels.statement_title}
            onChange={(e) => setLabels((prev) => ({ ...prev, statement_title: e.target.value }))}
          />
        </label>

        <label className="space-y-1">
          <span className="text-sm font-medium">Statement Subtitle</span>
          <input
            className="w-full bg-secondary border border-border rounded-md px-3 py-2 text-sm"
            value={labels.statement_subtitle}
            onChange={(e) => setLabels((prev) => ({ ...prev, statement_subtitle: e.target.value }))}
          />
        </label>

        <label className="space-y-1">
          <span className="text-sm font-medium">Invoice Footer Note</span>
          <textarea
            rows={3}
            className="w-full bg-secondary border border-border rounded-md px-3 py-2 text-sm"
            value={labels.invoice_footer_note}
            onChange={(e) => setLabels((prev) => ({ ...prev, invoice_footer_note: e.target.value }))}
          />
        </label>

        <label className="space-y-1">
          <span className="text-sm font-medium">Voucher Footer Note</span>
          <textarea
            rows={3}
            className="w-full bg-secondary border border-border rounded-md px-3 py-2 text-sm"
            value={labels.voucher_footer_note}
            onChange={(e) => setLabels((prev) => ({ ...prev, voucher_footer_note: e.target.value }))}
          />
        </label>
      </div>

      <Button onClick={save} disabled={saving}>{saving ? "Saving..." : "Save Content Labels"}</Button>
    </div>
  );
}
